CC = gcc
CFLAGS = -Wall -Wextra -std=c11

SRC_DIR = src
LIBRARY_SOURCES = $(SRC_DIR)/csv_parser.c
LIBRARY_HEADERS = $(SRC_DIR)/csv_parser.h
LIBRARY_OBJECTS = csv_parser.o

EXAMPLES_DIR = examples
MAIN_PROGRAM = $(EXAMPLES_DIR)/parse_csv_file.c
EXECUTABLE = $(EXAMPLES_DIR)/parse_csv_file

all: $(EXECUTABLE)

$(EXECUTABLE): $(LIBRARY_OBJECTS) $(MAIN_PROGRAM)
	$(CC) $(CFLAGS) -o $@ $(MAIN_PROGRAM) $(LIBRARY_OBJECTS)

$(LIBRARY_OBJECTS): $(LIBRARY_SOURCES) $(LIBRARY_HEADERS)
	$(CC) $(CFLAGS) -c $(LIBRARY_SOURCES)

clean:
	rm -f $(EXECUTABLE) $(LIBRARY_OBJECTS)
