name: Build

on: [push, pull_request]

jobs:
  permissions:
    checks: write

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up C/C++
      run: sudo apt-get install build-essential

    - name: Set up Python 3
      run: sudo apt-get install python3

    - name: Build
      run: make

    - name: Run Test
      run: make test

    - name: Convert Test Result to JUnit
      run: python3 test/convert_to_junit_result.py

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v4
      if: success() || failure() # always run even if the previous step fails
      with:
        report_paths: 'test/result/*.xml'
        permissions:
          checks: write
